package io.github.milczekt1.corral.rules.java.serializablemustdeclareserialversionuid;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;

import com.tngtech.archunit.base.DescribedPredicate;
import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.JavaField;
import com.tngtech.archunit.core.domain.JavaModifier;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchCondition;
import com.tngtech.archunit.lang.ArchRule;
import com.tngtech.archunit.lang.ConditionEvents;
import com.tngtech.archunit.lang.SimpleConditionEvent;
import io.github.milczekt1.corral.DocumentedRule;
import io.github.milczekt1.corral.doc.RuleDoc;
import java.io.Serializable;
import java.util.Optional;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;

/**
 * A class that itself declares an interface assignable to {@code Serializable} — the interface, {@code
 * Externalizable}, or a project interface extending either — must declare a
 * {@code static final long serialVersionUID}.
 *
 * <p>Stands alone, in no group: wire it with
 * {@code ArchTests.in(SerializableMustDeclareSerialVersionUidRule.class)}.
 *
 * <p>Only interfaces the class declares itself are read, so a subclass of a serializable base — every
 * custom exception included — is not checked. Do not widen this to
 * {@code assignableTo(Serializable.class)}: every {@code Throwable} would match. Access level is not
 * checked; the JVM honours the field at any.
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class SerializableMustDeclareSerialVersionUidRule implements DocumentedRule {

    static final String FIELD_NAME = "serialVersionUID";

    static final RuleDoc DOC = RuleDoc.builder()
            .id("corral.java.serializable-must-declare-serial-version-uid")
            .why("""
                    Without an explicit serialVersionUID the JVM computes one by hashing the class's \
                    structure — its name, modifiers, interfaces, field names and types, and method \
                    signatures. Adding a field, changing a method's visibility, or a compiler emitting a \
                    synthetic member changes the hash, so a class nobody meaningfully edited becomes \
                    incompatible with its own serialized form. The failure lands far from the edit: during \
                    a rolling deploy the new nodes cannot read sessions replicated by the old ones, so users \
                    are logged out depending on which instance they hit; every distributed-cache entry \
                    raises InvalidClassException: local class incompatible and the cache degrades to a \
                    miss on every read under full load; a queued message written by last week's version \
                    becomes permanently unreadable. The rule also makes an author notice that the class is \
                    serializable at all — every Serializable type is one more class an ObjectInputStream \
                    can be made to instantiate.""")
            .howToFix("""
                    First decide whether the class is actually serialized — most are not. If it is not, \
                    delete implements Serializable instead: that is the better fix in most cases, because \
                    it removes the class from the deserialization attack surface and lifts a constraint on \
                    every future field change, and it is usually free, since the interface came from a \
                    template or from a framework requirement that no longer applies. If it really is \
                    serialized, declare private static final long serialVersionUID and treat it as part of \
                    the contract: keep it stable while the serialized form stays compatible, and change it \
                    deliberately when it does not. Its value depends on whether instances already exist \
                    anywhere — in sessions, caches, queues or files. If none do, use 1L. If any do, they \
                    were written under the uid the JVM computed, so declare exactly the value the serialver \
                    tool prints for the class as currently deployed; any other value, 1L included, makes \
                    every existing instance unreadable. A field that is not static and final is ignored by \
                    the JVM, so the same applies when you fix one. A field of type int, short, byte or char \
                    is widened and used, so keep its value and change only the type to long.""")
            .howNotToFix("""
                    Do NOT add a serialVersionUID, generated by a tool or otherwise, to a class you have \
                    not established is serialized: that pins the compatibility promise instead of removing \
                    it, and the class stays on the deserialization surface. Do NOT move implements \
                    Serializable onto an abstract base class so the concrete types stop matching while \
                    every one of them is still serializable — this rule checks only classes that declare \
                    the interface themselves, so it does not catch that dodge. Do NOT drop static or final \
                    from the field or box it as Long: the JVM then ignores it and falls back to the \
                    computed uid, so the field looks right and does nothing. Do NOT add \
                    @SuppressWarnings("serial"): it silences javac and changes nothing here. Do NOT add the \
                    new violation to the freeze store by hand; the store records what existed at adoption, \
                    not what you just wrote.""")
            .build();

    static final ArchRule DEFINITION = classes()
            .that(declareASerializableInterface())
            .and().areNotEnums()
            .and().areNotRecords()
            .and().areNotInterfaces()
            .should(declareAStaticFinalLongSerialVersionUid());

    @ArchTest
    public static final ArchRule rule = new SerializableMustDeclareSerialVersionUidRule().guard();

    @Override
    public ArchRule definition() {
        return DEFINITION;
    }

    @Override
    public RuleDoc doc() {
        return DOC;
    }

    private static DescribedPredicate<JavaClass> declareASerializableInterface() {
        return DescribedPredicate.describe("declare an interface assignable to Serializable",
                javaClass -> javaClass.getRawInterfaces().stream()
                        .anyMatch(type -> type.isAssignableTo(Serializable.class)));
    }

    private static ArchCondition<JavaClass> declareAStaticFinalLongSerialVersionUid() {
        return new ArchCondition<>("declare a static final long " + FIELD_NAME) {
            @Override
            public void check(JavaClass javaClass, ConditionEvents events) {
                Optional<JavaField> field = javaClass.tryGetField(FIELD_NAME);
                if (field.isEmpty()) {
                    events.add(SimpleConditionEvent.violated(javaClass, "Class <" + javaClass.getFullName()
                            + "> declares no " + FIELD_NAME + " in " + javaClass.getSourceCodeLocation()));
                } else if (!isStaticFinalLong(field.get())) {
                    events.add(SimpleConditionEvent.violated(field.get(), "Field <" + field.get().getFullName()
                            + "> is not static final long in " + field.get().getSourceCodeLocation()));
                }
            }
        };
    }

    private static boolean isStaticFinalLong(JavaField field) {
        return field.getModifiers().contains(JavaModifier.STATIC)
                && field.getModifiers().contains(JavaModifier.FINAL)
                && field.getRawType().isEquivalentTo(long.class);
    }
}
